### ISSUE TITLE
Gender information of the database

### ISSUE THREAD

**Issue by kristosh** [CheyneyComputerScience/CREMA-D#1]
Is it store somewhere the analytics per person, (age, gender etc)?

**Comment by DavidCooperWCU** [comment]
I think you are asking about demographics for each person in the videos: [VideoDemographics.csv](https://github.com/CheyneyComputerScience/CREMA-D/blob/master/VideoDemographics.csv) has that information.

Please close this issue if this answers your question. Otherwise, please clarify.
