### ISSUE TITLE
Damaged Video Files

### ISSUE THREAD

**Issue by robert-DL** [CheyneyComputerScience/CREMA-D#12]
After downloading with git-lfs, one obtains all the sound files but unfortunately, the video files are corrupted. They have an average size of 300 kb and can't be played.

**Comment by DavidCooperWCU** [comment]
The flash video files aren't corrupt, though it's possible that the program you are using can't read the particular flash video format that is used. VLC should work as should ffplay and ffmpeg.

If you need to convert from .flv to .mp4, you can you ffmpeg as follows:

```
ffmpeg -i 1015_DFA_ANG_XX.flv  1015_DFA_ANG_XX.mp4
```

**Comment by robert-DL** [comment]
Stupid me! Obviously, I should have changed to VLC. Thx for reminding me!
