### ISSUE TITLE
Evaluation Protocol

### ISSUE THREAD

**Issue by EsamGhaleb** [CheyneyComputerScience/CREMA-D#2]
Hi, 
I am planning to use this dataset in my work. I am wondering if you have an evaluation protocol for the cross validation where you provide the information for the train, test, and validation sets?

**Comment by DavidCooperWCU** [comment]
That's a good question. We have not separated the data nor do we have an evaluation protocol for the data set. Users of the data set are encouraged to create their own evaluation protocol for the purposes of their research. 

It may take some time to look at the data that are provided before you'll be able to determine a plan of approach for using the data set in your research, and hopefully at least one aspect of the data set will satisfy your research needs.

As a reminder, when separating the data, it is important that files of each actor are grouped together. If they are not, it can contaminate the results. 

Please look at the filename labeling conventions in the Readme.md file in the home page of this repository for more information.
