### ISSUE TITLE
Bad data

### ISSUE THREAD

**Issue by ruanxiu520** [CheyneyComputerScience/CREMA-D#8]
For audio data, '1076_MTI_NEU_XX.mp3' and '1076_MTI_NEU_XX.wav' can't play, and '1076_MTI_SAD_XX.mp3' and '1076_MTI_SAD_XX.wav' can play but there is no sound.  
For video data, '1076_MTI_NEU_XX.flv' has no sound, and '1076_MTI_SAD_XX.flv' has no face which looks like below.
![image](https://user-images.githubusercontent.com/56337600/115159067-f1c1aa00-a0c3-11eb-95fb-f771f79fcca5.png)

Looking forward to the correct data!

**Comment by ruanxiu520** [comment]
> For audio data, '1076_MTI_NEU_XX.mp3' and '1076_MTI_NEU_XX.wav' can't play, and '1076_MTI_SAD_XX.mp3' and '1076_MTI_SAD_XX.wav' can play but there is no sound.
> For video data, '1076_MTI_NEU_XX.flv' has no sound, and '1076_MTI_SAD_XX.flv' has no face which looks like below.
> ![image](https://user-images.githubusercontent.com/56337600/115159067-f1c1aa00-a0c3-11eb-95fb-f771f79fcca5.png)
> 
> Looking forward to the correct data!

I find other bad data. 
'1064_TIE_SAD_XX.mp3' and '1064_TIE_SAD_XX.flv' have no duration.
'1064_IEO_DIS_MD.mp3' and '1064_IEO_DIS_MD.flv' have a duration of '1:01', and both contain different kinds of emotion.
![image](https://user-images.githubusercontent.com/56337600/115284367-2f373d80-a17f-11eb-99bd-67daccf056e8.png)

**Comment by shivangpatel** [comment]
Yes. Many of the files are unable to play/read. Maybe data is corrupted somehow...

**Comment by Coding511** [comment]
Actually none is playing. @shivangpatel Have you got any correct dataset?

**Comment by shivangpatel** [comment]
> Actually none is playing. @shivangpatel Have you got any correct dataset?

No!!!

**Comment by tanishqvyas** [comment]
@shivangpatel @ruanxiu520 @Coding511 @nenkova @houweicao The data is not corrupt. You have to clone the repository in the correct fashion

**Comment by shivangpatel** [comment]
> @shivangpatel @ruanxiu520 @Coding511 @nenkova @houweicao The data is not corrupt. You have to clone the repository in the correct fashion

So, Can you answer it? In which way we can do it correctly? It will help us a lot.

**Comment by tanishqvyas** [comment]
@shivangpatel 
Install `git-lfs` by refering to [this](https://docs.github.com/en/repositories/working-with-files/managing-large-files/installing-git-large-file-storage) then run

```bash
git lfs clone <repository-url>
```

**Comment by antonio-t** [comment]
The data indicated by user ruanxiu520 is still faulty to this day. Any solution by the authors? I think they should be at least listed somehow in the main README file, so people avoid using them for training a machine learning method, etc.

**Comment by DavidCooperWCU** [comment]
@antonio-t, thanks for the suggestion. If the data is faulty, it was also faulty for the raters, so "correcting" the data would make the ratings invalid because they wouldn't be associated with what was rated.

I will put a note in the readme about the fact that some files have been identified as being either incomplete or not matching their description.

**Comment by DavidCooperWCU** [comment]
Readme.md was updated so future users will know about the file oddities.
